name: Azure Web App Deploy

on:
  push:
    branches:
      - master  # 或你實際的分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: xiaomi-bodyfat
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: .
